version: '3.6'

services:
  mysql:
    image: mariadb:latest
    ports:
      - "3397:3306"
    container_name: lockity_mysql
    volumes:
      - '.docker/conf.d/mysql.cnf:/etc/mysql/conf.d/docker.cnf:ro'
    environment:
      MYSQL_DATABASE: lockity
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
